---
#pip tasks

- name: Get pip install script
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    mode: 755
    owner: root
    group: root

- name: Install pip
  command: python /tmp/get-pip.py
  args:
    creates: "/usr/local/bin/pip"
    chdir: /tmp

- name: Install pip3
  apt:
      name: "python3-pip"
      state: latest
      force: yes
